---

name: "Create Release Branch to DMZ Pull Request"
on:
  # pull_request:
  push:
    branches:
      - 'test*'
jobs:
  open_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x ./github_action_scripts/open_pr.sh
          ./github_action_scripts/open_pr.sh ${GITHUB_API_URL} ${GITHUB_REPOSITORY} ${GITHUB_REF_NAME} ${secrets.GITHUB_TOKEN}
        shell: bash
